url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Yasin Simsek" # the name of your site, e.g. ACME Corp.
description: "PhD Candidate at Duke University" # a short description of site's purpose
