menu:
- {name: 'Research', url: '/research'}
- {name: 'Teaching', url: '/courses'}
- {name: 'Resume', url: '/resume'}
- {name: 'Contact', url: '/contact'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/yasin-simsek'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/yasin-simsek-47b8462b3'}

contacts:
- {name: 'Dr. Academia', title: 'Professor', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/contact.jpg'}
