menu:
- {name: 'RESEARCH', url: '/research'}
- {name: 'TEACHING', url: '/teaching'}
- {name: 'CV', url: '/cv'}
#- {name: 'Contact', url: '/contact'}

# courses:
# - {name: 'Vector Calculus', url: 'vector-calculus'}
# - {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
# - {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'fab fa-github', link: 'https://github.com/yasin-simsek'}
- {icon: 'fab fa-linkedin', link: 'https://www.linkedin.com/in/yasin-simsek-47b8462b3'}
- {icon: 'fas fa-graduation-cap', link: 'https://scholar.google.com/citations?user=aGapKucAAAAJ&hl=en'}

contacts:
- {name: 'Yasin Simsek', title: 'PhD Candidate', department: 'Department of Economics', institution: 'Duke University', institution_address: '419 Chapel Drive, Durham, NC, US', phone: '919-660-1800', email: 'yasin.simsek@duke.edu', office: 'Social Sciences Building 325', image: 'assets/img/duke.jpeg'}
